//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDMS_MVC_WEB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_1_State_Code
    {
        public string C1_ST_Code { get; set; }
        public string State_Alph { get; set; }
        public string State_Name { get; set; }
    }
}
